param
(
)

if ($Env:APPVEYOR_REPO_TAG -eq $true) {
	$outputPath = Join-Path $PSScriptRoot "sidfeeds"
	$packageVersion = $Env:APPVEYOR_REPO_TAG_NAME
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Common\SimpleIdentityServer.Module /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Common\SimpleIdentityServer.AccessToken.Store /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Common\SimpleIdentityServer.AccessToken.Store.InMemory /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Common\SimpleIdentityServer.Logging /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Common\SimpleIdentityServer.Common.Client /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Common\SimpleIdentityServer.Common.Dtos /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Uma\SimpleIdentityServer.Uma.Client /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Uma\SimpleIdentityServer.Uma.Common /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Uma\SimpleIdentityServer.Uma.Core /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Uma\SimpleIdentityServer.Uma.EF /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Uma\SimpleIdentityServer.Uma.EF.InMemory /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Uma\SimpleIdentityServer.Uma.EF.Postgre /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Uma\SimpleIdentityServer.Uma.EF.Sqlite /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Uma\SimpleIdentityServer.Uma.EF.SqlServer /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Uma\SimpleIdentityServer.Uma.Host /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Uma\SimpleIdentityServer.Uma.Store.Redis /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Uma\SimpleIdentityServer.Uma.Store.InMemory /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Uma\SimpleIdentityServer.Uma.Logging /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.UserManagement /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.Shell /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.Authenticate.Basic /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.Authenticate.LoginPassword /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.Authenticate.SMS /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.Authenticate.SMS.Client /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.Authenticate.SMS.Common /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.Client /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.Core /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.Core.Common /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.Core.Jwt /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.EF /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.EF.InMemory /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.EF.Postgre /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.EF.Sqlite /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.EF.SqlServer /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.OpenId.Events /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.OAuth.Events /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.OpenId.Logging /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.OAuth.Logging /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.Host /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.OAuth2Introspection /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.Store /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.Store.Redis /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.Store.InMemory /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.TwoFactorAuthentication /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.TwoFactorAuthentication.Email /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.TwoFactorAuthentication.Twilio /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.UserInfoIntrospection /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.Twilio.Client /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.AccountFilter /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.AccountFilter.Basic /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.AccountFilter.Basic.EF /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.AccountFilter.Basic.EF.InMemory /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.AccountFilter.Basic.EF.Postgre /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.AccountFilter.Basic.EF.Sqlite /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\SimpleIdServer\SimpleIdentityServer.AccountFilter.Basic.EF.SqlServer /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Scim\SimpleIdentityServer.Scim.Client /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Scim\SimpleIdentityServer.Scim.Events /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Scim\SimpleIdentityServer.Scim.Common /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Scim\SimpleIdentityServer.Scim.Core /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Scim\SimpleIdentityServer.Scim.Db.EF /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Scim\SimpleIdentityServer.Scim.Db.EF.InMemory /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Scim\SimpleIdentityServer.Scim.Db.EF.Postgre /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Scim\SimpleIdentityServer.Scim.Db.EF.Sqlite /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Scim\SimpleIdentityServer.Scim.Db.EF.SqlServer /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Apis\Scim\SimpleIdentityServer.Scim.Host /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Lib\System.Security.Cryptography.Algorithms.Extensions /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Lib\WsFederation /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Lib\Serilog\Serilog.Sinks.ElasticSearch /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Lib\Serilog\Serilog.Sinks.RabbitMQ /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Lib\WebApiContrib\WebApiContrib.Core.Concurrency /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Lib\WebApiContrib\WebApiContrib.Core.Storage /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Lib\WebApiContrib\WebApiContrib.Core.Storage.InMemory /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Lib\WebApiContrib\WebApiContrib.Core.Storage.Redis /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Lib\Bus\SimpleBus.Core /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath IdServer\SimpleIdentityServer\src\Lib\Bus\SimpleBus.InMemory /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\Profile\SimpleIdentityServer.Profile.Core /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\Profile\SimpleIdentityServer.Profile.EF /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\Profile\SimpleIdentityServer.Profile.EF.InMemory /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\Profile\SimpleIdentityServer.Profile.EF.Postgre /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\Profile\SimpleIdentityServer.Profile.EF.Sqlite /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\Profile\SimpleIdentityServer.Profile.EF.SqlServer /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\Profile\SimpleIdentityServer.Profile.Host /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\Manager\SimpleIdentityServer.Manager.Client /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\Manager\SimpleIdentityServer.Manager.Common /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\Manager\SimpleIdentityServer.Manager.Logging /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\Manager\SimpleIdentityServer.Manager.Core /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\Manager\SimpleIdentityServer.Manager.Host /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\HierarchicalResource\SimpleIdentityServer.HierarchicalResource.Client /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\HierarchicalResource\SimpleIdentityServer.HierarchicalResource.Common /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\HierarchicalResource\SimpleIdentityServer.HierarchicalResource.Core /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\HierarchicalResource\SimpleIdentityServer.HierarchicalResource.EF /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\HierarchicalResource\SimpleIdentityServer.HierarchicalResource.EF.InMemory /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\HierarchicalResource\SimpleIdentityServer.HierarchicalResource.EF.Postgre /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\HierarchicalResource\SimpleIdentityServer.HierarchicalResource.EF.Sqlite /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\HierarchicalResource\SimpleIdentityServer.HierarchicalResource.EF.SqlServer /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\HierarchicalResource\SimpleIdentityServer.HierarchicalResource.Host /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\HierarchicalResource\SimpleIdentityServer.HierarchicalResource.Resolver /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\EventStore\SimpleIdentityServer.EventStore.Core /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\EventStore\SimpleIdentityServer.EventStore.EF /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\EventStore\SimpleIdentityServer.EventStore.Host /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\EventStore\SimpleIdentityServer.EventStore.InMemory /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\EventStore\SimpleIdentityServer.EventStore.Postgre /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\EventStore\SimpleIdentityServer.EventStore.Sqlite /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\EventStore\SimpleIdentityServer.EventStore.SqlServer /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\License\SimpleIdentityServer.License /p:PackageVersion=$packageVersion /p:Version=$packageVersion
	dotnet pack --output $outputPath SimpleIdentityServer\src\Apis\Uma\SimpleIdentityServer.Uma.Authentication /p:PackageVersion=$packageVersion /p:Version=$packageVersion
}