START cmd /k "cd src/Apis/Eid/SimpleIdentityServer.Eid.OpenId && dotnet run -f net461"
START cmd /k "cd src/Apis/Eid/SimpleIdentityServer.Eid.UI && dotnet electronize start"
echo Applications are running ...