import Dashboard from './dashboard';
import About from './about';
import Login from './login';
import Logs from './logs';
import Resources from './resources';
import ViewAggregate from './viewAggregate';
import ViewLog from './viewLog';
import Clients from './clients';
import Scopes from './scopes';
import ResourceOwners from './resourceOwners';
import ViewResource from './viewResource';
import ViewClient from './viewClient';
import ViewScope  from './viewScope';
import ViewResourceOwner from './viewResourceOwner';
import Claims from './claims';
import ViewClaim from './viewClaim';
import ScimSchemas from './scimSchemas';
import ScimResources from './scimResources';
import ViewScimSchema from './viewScimSchema';
import ViewScimAttribute from './viewScimAttribute';
import ViewScimResource from './viewScimResource';
import Settings from './settings';
import ViewSetting from './viewSetting';
import Connectors from './connectors';
import TwoFactors from './twoFactors';

exports.Dashboard = Dashboard;
exports.About = About;
exports.Login = Login;
exports.Logs = Logs;
exports.Resources = Resources;
exports.ViewLog = ViewLog;
exports.ViewAggregate = ViewAggregate;
exports.Clients = Clients;
exports.Scopes = Scopes;
exports.ResourceOwners = ResourceOwners;
exports.ViewResource = ViewResource;
exports.ViewClient = ViewClient;
exports.ViewScope = ViewScope;
exports.ViewResourceOwner = ViewResourceOwner;
exports.Claims = Claims;
exports.ViewClaim = ViewClaim;
exports.ScimSchemas = ScimSchemas;
exports.ScimResources = ScimResources;
exports.ViewScimSchema = ViewScimSchema;
exports.ViewScimAttribute = ViewScimAttribute;
exports.ViewScimResource = ViewScimResource;
exports.Settings = Settings;
exports.ViewSetting = ViewSetting;
exports.Connectors = Connectors;
exports.TwoFactors = TwoFactors;