import Dashboard from './dashboard';
import About from './about';
import Login from './login';
import Logs from './logs';
import Resources from './resources';
import ViewAggregate from './viewAggregate';
import ViewLog from './viewLog';
import OAuthClients from './oauthClients';
import OpenidClients from './openidClients';
import OAuthScopes from './oauthScopes';
import OpenidScopes from './openidScopes';
import ResourceOwners from './resourceOwners';
import ViewResource from './viewResource';
import ViewOpenidClient from './viewOpenidClient';
import ViewAuthClient from './viewAuthClient';
import ViewScope  from './viewScope';
import AddScope from './addScope';
import ViewUser from './viewUser';
import Claims from './claims';
import ViewClaim from './viewClaim';
import ScimSchemas from './scimSchemas';
import ScimResources from './scimResources';
import ViewScimSchema from './viewScimSchema';
import ViewScimAttribute from './viewScimAttribute';
import ViewScimResource from './viewScimResource';
import Settings from './settings';
import ViewSetting from './viewSetting';
import Connectors from './connectors';
import TwoFactors from './twoFactors';

exports.Dashboard = Dashboard;
exports.About = About;
exports.Login = Login;
exports.Logs = Logs;
exports.Resources = Resources;
exports.ViewLog = ViewLog;
exports.ViewAggregate = ViewAggregate;
exports.OAuthClients = OAuthClients;
exports.OpenidClients = OpenidClients;
exports.OAuthScopes = OAuthScopes;
exports.OpenidScopes = OpenidScopes;
exports.ResourceOwners = ResourceOwners;
exports.ViewResource = ViewResource;
exports.ViewOpenidClient = ViewOpenidClient;
exports.ViewAuthClient = ViewAuthClient;
exports.ViewScope = ViewScope;
exports.AddScope = AddScope;
exports.ViewUser = ViewUser;
exports.Claims = Claims;
exports.ViewClaim = ViewClaim;
exports.ScimSchemas = ScimSchemas;
exports.ScimResources = ScimResources;
exports.ViewScimSchema = ViewScimSchema;
exports.ViewScimAttribute = ViewScimAttribute;
exports.ViewScimResource = ViewScimResource;
exports.Settings = Settings;
exports.ViewSetting = ViewSetting;
exports.Connectors = Connectors;
exports.TwoFactors = TwoFactors;