import SessionService from './sessionService';
import WebsiteService from './websiteService';
import EndpointService from './endpointService';
import ClientService from './clientService';
import ScopeService from './scopeService';
import ResourceOwnerService from './resourceOwnerService';
import ResourceService from './resourceService';
import ProfileService from './profileService';
import ClaimService from './claimService';
import AuthPolicyService from './authPolicyService';
import ScimService from './scimService';
import ParameterService from './parameterService';

exports.SessionService = SessionService;
exports.WebsiteService = WebsiteService;
exports.EndpointService = EndpointService;
exports.ClientService = ClientService;
exports.ScopeService = ScopeService;
exports.ResourceOwnerService = ResourceOwnerService;
exports.ResourceService = ResourceService;
exports.ProfileService = ProfileService;
exports.ClaimService = ClaimService;
exports.AuthPolicyService = AuthPolicyService;
exports.ScimService = ScimService;
exports.ParameterService = ParameterService;